Distance and closest point
20chan/cirno pull request #7
Opened 2019-10-14 04:35 UTC by Guarionex

Addresses information between a shape and a point on issue #5

2019-10-14 07:33 UTC, 20chan commented
Your all changes have formatting issues. This project uses [K&R indenting style](https://en.wikipedia.org/wiki/Indentation_style#K&R_style).

Can you change all of your changes? I'm really sorry for no .editorconfig or contributing docs. My VS2019 has problem with generating editorconfig file.

2019-10-14 07:37 UTC, 20chan requested changes

2019-10-14 07:37 UTC, 20chan commented on cirno/Vector.cs
> +            return (float) Math.Sqrt(xPowDif + yPowDif);
Can you remove whitespace after type casts?

2019-10-14 07:37 UTC, 20chan commented on cirno.Tests/Geometry/TestHelpers.cs
> +            return BitConverter.ToSingle(buffer,0);
Can you add whitespace after comma?

2019-10-14 07:37 UTC, 20chan commented on cirno.Tests/Geometry/CircleTest.cs
> +using System;
Can you change ALL indent styles to K&R styles?

2019-10-14 13:18 UTC, Guarionex commented
@20chan yeah I can make those changes later today

2019-10-15 01:14 UTC, Guarionex commented
@20chan I've made the changes. Let me know if I missed one. Also the random float generator is kinda flaky due to overflow when squaring. I square root the random float to avoid overflow when squaring in the unit tests. I recommend you look into style cop as a linter to regulate code styles

2019-10-15 01:56 UTC, 20chan requested changes
Thank you for all these changes, only one more change left.

2019-10-15 01:56 UTC, 20chan commented on cirno.Tests/Geometry/LineTest.cs
> +        public void GivenLine_WhenCallingDistanceToAPoint_ThenReturnDistance(){
Can you add whitespace before brace?

```csharp
method() {
```

2019-10-15 02:21 UTC, Guarionex commented on cirno.Tests/Geometry/LineTest.cs
> +        public void GivenLine_WhenCallingDistanceToAPoint_ThenReturnDistance(){
Done

2019-10-15 03:38 UTC, 20chan approved these changes

2019-10-15 03:38 UTC, merged

2019-10-15 03:41 UTC, 20chan commented on cirno/Geometry/LineLike.cs
> +            if (float.IsInfinity(slope))
Wait I missed this one.....